# Generated by Django 5.2.5 on 2025-08-30 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_book_published_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='BookRahe',
        ),
    ]
