# Generated by Django 5.2.6 on 2025-09-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to='cover_images/'),
        ),
    ]
