# Generated by Django 5.2.6 on 2025-09-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(default='bogura', max_length=70),
            preserve_default=False,
        ),
    ]
