# Generated by Django 5.2.5 on 2025-08-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='des',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
