# Generated by Django 5.2.5 on 2025-08-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_author_book_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='des',
            field=models.TextField(null=True),
        ),
    ]
